AWSTemplateFormatVersion: "2010-09-09"

Description: AWS Account Resource

Parameters:
  ProductID:
    Description: ""
    Type: String
    Default: example
  DomainName:
    Description: ""
    Type: String
    Default: example.com

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: ""
      Name: !Sub ${ProductID}.${DomainName}.
      QueryLoggingConfig:
        CloudWatchLogsLogGroupArn: !Sub "arn:aws:logs:us-east-1:${AWS::AccountId}:log-group:/aws/hostedzone/${ProductID}.${DomainName}"

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "*.${ProductID}.${DomainName}"
      DomainValidationOptions:
        - DomainName: !Sub "*.${ProductID}.${DomainName}"
          ValidationDomain: !Sub "${ProductID}.${DomainName}"
      SubjectAlternativeNames:
        - !Sub "${ProductID}.${DomainName}"
      ValidationMethod: "DNS"

  CloudTrailS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub cloudtrail.${ProductID}.${DomainName}
      Tags:
        - Key: Name
          Value: !Sub cloudtrail.${ProductID}.${DomainName}
        - Key: ProductID
          Value: !Ref ProductID

  CloudTrailS3BucketPolicy:
    DependsOn: S3BucketLog
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudTrailS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ALBLogBucketPolicy
            Effect: Allow
            Principal:
              AWS:
                - 582318560864 # ap-northeast-1
                - 127311923021 # us-east-1
                - 033677994240 # us-east-2
                - 027434742980 # us-west-1
                - 797873946194 # us-west-2
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub arn:aws:s3:::${CloudTrailS3Bucket}
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${CloudTrailS3Bucket}/AWSLogs/${AWS::AccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  CloudTrail:
    DependsOn: BucketPolicy
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName: !Sub cloudtrail.${ProductID}.${DomainName}
      IncludeGlobalServiceEvents: true
      EnableLogFileValidation: true
      IsMultiRegionTrail: true
      IsLogging: true
      Tags:
        - Key: Name
          Value: !Sub cloudtrail.${ProductID}.${DomainName}
        - Key: ProductID
          Value: !Ref ProductID

  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true
