AWSTemplateFormatVersion: '2010-09-09'

Description:
  AWS RDS(Aurora) Resource

Parameters:
  ProjectName:
    Description: ""
    Type: String
    Default: example
  MasterUsername:
    Description: ""
    Type: String
  MasterUserPassword:
    Description: ""
    Type: String
  DBInstanceClass:
    Description: ""
    Type: String
    Default: "db.t2.medium"
    AllowedValues:
      - db.t2.medium
      - db.r3.large
      - db.r3.xlarge
      - db.r3.2xlarge
      - db.r3.4xlarge
      - db.r3.8xlarge
  DBSnapshotName:
    Description: ""
    Type: String
    Default: ""
  PubliclyAccessible:
    Description: ""
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  MultiAZ:
    Description: ""
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  SubnetA:
    Description: ""
    Type: String
  SubnetC:
    Description: ""
    Type: String

Conditions:
  UseDBSnapshot: !Not [!Equals [ !Ref DBSnapshotName, "" ]]
  IsMultiAZ: !Equals [ !Ref MultiAZ, "true" ]

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "DBSubnetGroup"
      SubnetIds:
        - !Ref SubnetA
        - !Ref SubnetC

  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: ""
      Family: "aurora5.6"
      Parameters:
        character_set_database: "utf8"

  DBCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: "Snapshot"
    Properties:
      Engine: "aurora"
      MasterUsername: !If
        - UseDBSnapshot
        - !Ref AWS::NoValue
        - !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      VpcSecurityGroupIds:
        - { "Fn::ImportValue": !Sub "${ProjectName}-PrivateSecurityGroup"}
      SnapshotIdentifier: !If
        - UseDBSnapshot
        - !Ref DBSnapshotName
        - !Ref AWS::NoValue

  DBInstanceA:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: "aurora"
      DBClusterIdentifier: !Ref DBCluster
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBInstanceClass: !Ref DBInstanceClass
      PubliclyAccessible: !Ref PubliclyAccessible
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: DBSnapshotName
          Value: !Ref DBSnapshotName

  DBInstanceC:
    Type: AWS::RDS::DBInstance
    Condition: IsMultiAZ
    Properties:
      Engine: "aurora"
      DBClusterIdentifier: !Ref DBCluster
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBInstanceClass: !Ref DBInstanceClass
      PubliclyAccessible: !Ref PubliclyAccessible
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: DBSnapshotName
          Value: !Ref DBSnapshotName
