AWSTemplateFormatVersion: '2010-09-09'

Description:
  AWS Content Delivery Network Resource

Parameters:
  ProjectName:
    Description: ""
    Type: String
    Default: example
  Environment:
    Description: ""
    Type: String
    Default: dev
  Role:
    Description: ""
    Type: String
    Default: default
  DomainName:
    Description: ""
    Type: String
    Default: example.com
