AWSTemplateFormatVersion: '2010-09-09'

Description:
  AWS Database Resource

Parameters:
  ProjectName:
    Description: ""
    Type: String
  Environment:
    Description: ""
    Type: String
    Default: dev
  MasterUsername:
    Description: ""
    Type: String
  MasterUserPassword:
    Description: ""
    Type: String
  DBInstanceClass:
    Description: ""
    Type: String
    Default: "db.t2.medium"
    AllowedValues:
      - db.t2.medium
      - db.r3.large
      - db.r3.xlarge
      - db.r3.2xlarge
      - db.r3.4xlarge
      - db.r3.8xlarge
  MultiAZ:
    Description: ""
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  DeletionPolicy:
    Description: ""
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

Conditions:
  UseDBSnapshot: !Not [!Equals [ !Ref DBSnapshotName, "" ]]
  IsMultiAZ: !Equals [ !Ref MultiAZ, "true" ]

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "DBSubnetGroup"
      SubnetIds:
        - !Ref SubnetA
        - !Ref SubnetC

  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: ""
      Family: "aurora5.6"
      Parameters:
        character_set_database: "utf8"

  DBParameterGroup:
    Type: "AWS::RDS::DBParameterGroup"
    Properties:
      Description: ""
      Family: "aurora5.6"
      Parameters:
        slow_query_log: 1
        long_query_time: 1

  DBCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: "Snapshot"
    Properties:
      Engine: "aurora"
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      DeletionPolicy: !Ref DeletionPolicy
      VpcSecurityGroupIds:
        - !Sub '{{resolve:ssm:/${ProjectName}/${Environment}/PrivateSecurityGroup:1}}'

  DBInstanceA:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: "aurora"
      DBClusterIdentifier: !Ref DBCluster
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBParameterGroupName: !Ref DBParameterGroup
      DBInstanceClass: !Ref DBInstanceClass
      EnablePerformanceInsights: true
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  DBInstanceB:
    Type: AWS::RDS::DBInstance
    Condition: IsMultiAZ
    Properties:
      Engine: "aurora"
      DBClusterIdentifier: !Ref DBCluster
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBParameterGroupName: !Ref DBParameterGroup
      DBInstanceClass: !Ref DBInstanceClass
      EnablePerformanceInsights: true
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: DBSnapshotName
          Value: !Ref DBSnapshotName
