AWSTemplateFormatVersion: '2010-09-09'

Description:
  AWS Database Resource

Parameters:
  ProductName:
    Description: ""
    Type: String
    Default: example
  Environment:
    Description: ""
    Type: String
    Default: dev
  Role:
    Description: ""
    Type: String
    Default: default
  DomainName:
    Description: ""
    Type: String
    Default: example.com
  MasterUsername:
    Description: ""
    Type: String
  MasterUserPassword:
    Description: ""
    Type: String
  DBInstanceClass:
    Description: ""
    Type: String
    Default: db.t2.medium
    AllowedValues:
      - db.t2.medium
      - db.r3.large
      - db.r3.xlarge
      - db.r3.2xlarge
      - db.r3.4xlarge
      - db.r3.8xlarge
  MultiAZ:
    Description: ""
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  DeletionProtection:
    Description: ""
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

Conditions:
  MultiAZ: !Equals [ !Ref MultiAZ, "true" ]

Resources:
  SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "SubnetGroup"
      SubnetIds:
        - !Sub '{{resolve:ssm:/${ProductName}/${Environment}/PrivateSubnetA:1}}'
        - !Sub '{{resolve:ssm:/${ProductName}/${Environment}/PrivateSubnetB:1}}'
        - !Sub '{{resolve:ssm:/${ProductName}/${Environment}/PrivateSubnetC:1}}'

  ClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: "ClusterParameterGroup"
      Family: aurora5.6
      Parameters:
        character_set_client:     "utf8mb4"
        character_set_connection: "utf8mb4"
        character_set_database:   "utf8mb4"
        character_set_results:    "utf8mb4"
        character_set_server:     "utf8mb4"

  ParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: "ParameterGroup"
      Family: aurora5.6
      Parameters:
        slow_query_log: 1
        long_query_time: 1

  Cluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Snapshot
    Properties:
      Name: !Sub "${ProductName}.${Environment}.${Role}"
      Engine: aurora
      MasterUsername:     !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBSubnetGroupName:  !Ref SubnetGroup
      DeletionProtection: !Ref DeletionProtection
      DBClusterParameterGroupName: !Ref ClusterParameterGroup
      VpcSecurityGroupIds:
        - !Sub '{{resolve:ssm:/${ProductName}/${Environment}/PrivateSecurityGroup:1}}'

  InstanceA:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora
      DBClusterIdentifier:  !Ref Cluster
      DBSubnetGroupName:    !Ref SubnetGroup
      DBParameterGroupName: !Ref ParameterGroup
      DBInstanceClass:      !Ref DBInstanceClass
      EnablePerformanceInsights: true
      Tags:
        - Key: ProductName
          Value: !Ref ProductName
        - Key: Environment
          Value: !Ref Environment
        - Key: Role
          Value: !Ref Role

  InstanceB:
    Type: AWS::RDS::DBInstance
    Condition: MultiAZ
    Properties:
      Engine: aurora
      DBClusterIdentifier:  !Ref Cluster
      DBSubnetGroupName:    !Ref SubnetGroup
      DBParameterGroupName: !Ref ParameterGroup
      DBInstanceClass:      !Ref DBInstanceClass
      EnablePerformanceInsights: true
      Tags:
        - Key: ProductName
          Value: !Ref ProductName
        - Key: Environment
          Value: !Ref Environment
        - Key: Role
          Value: !Ref Role

  SSMEndpointAddress:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "EndpointAddress"
      Name: !Sub "/${ProductName}/${Environment}/database/${Role}/EndpointAddress"
      Value: !GetAtt DBCluster.Endpoint.Address
      Type: String

  SSMReadEndpointAddress:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "ReadEndpointAddress"
      Name: !Sub "/${ProductName}/${Environment}/database/${Role}/ReadEndpointAddress"
      Value: !GetAtt DBCluster.ReadEndpoint.Address
      Type: String

  SSMMasterUsername:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "MasterUsername"
      Name: !Sub "/${ProductName}/${Environment}/database/${Role}/MasterUsername"
      Value: !Ref MasterUsername
      Type: String

  SSMMasterUserPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "MasterUserPassword"
      Name: !Sub "/${ProductName}/${Environment}/database/${Role}/MasterUserPassword"
      Value: !Ref MasterUserPassword
      Type: String
