AWSTemplateFormatVersion: '2010-09-09'

Description:
  AWS Database Resource

Parameters:
  ProjectName:
    Description: ""
    Type: String
  Environment:
    Description: ""
    Type: String
    Default: dev
  Role:
    Description: ""
    Type: String
    Default: default
  MasterUsername:
    Description: ""
    Type: String
  MasterUserPassword:
    Description: ""
    Type: String
  DBInstanceClass:
    Description: ""
    Type: String
    Default: "db.t2.medium"
    AllowedValues:
      - db.t2.medium
      - db.r3.large
      - db.r3.xlarge
      - db.r3.2xlarge
      - db.r3.4xlarge
      - db.r3.8xlarge
  MultiAZ:
    Description: ""
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  DeletionProtection:
    Description: ""
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

Conditions:
  MultiAZ: !Equals [ !Ref MultiAZ, "true" ]

Resources:
  SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "SubnetGroup"
      SubnetIds:
        - !Sub '{{resolve:ssm:/${ProjectName}/${Environment}/PrivateSubnetA:1}}'
        - !Sub '{{resolve:ssm:/${ProjectName}/${Environment}/PrivateSubnetB:1}}'
        - !Sub '{{resolve:ssm:/${ProjectName}/${Environment}/PrivateSubnetC:1}}'

  ClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: "ClusterParameterGroup"
      Family: aurora5.6
      Parameters:
        character_set_database: utf8

  ParameterGroup:
    Type: "AWS::RDS::DBParameterGroup"
    Properties:
      Description: "ParameterGroup"
      Family: aurora5.6
      Parameters:
        slow_query_log: 1
        long_query_time: 1

  Cluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Snapshot
    Properties:
      Name: !Sub "${ProjectName}.${Environment}.${Role}"
      Engine: aurora
      MasterUsername:     !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBSubnetGroupName:  !Ref SubnetGroup
      DeletionProtection: !Ref DeletionProtection
      DBClusterParameterGroupName: !Ref ClusterParameterGroup
      VpcSecurityGroupIds:
        - !Sub '{{resolve:ssm:/${ProjectName}/${Environment}/PrivateSecurityGroup:1}}'

  InstanceA:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora
      DBClusterIdentifier:  !Ref Cluster
      DBSubnetGroupName:    !Ref SubnetGroup
      DBParameterGroupName: !Ref ParameterGroup
      DBInstanceClass:      !Ref DBInstanceClass
      EnablePerformanceInsights: true
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Role
          Value: !Ref Role

  InstanceB:
    Type: AWS::RDS::DBInstance
    Condition: MultiAZ
    Properties:
      Engine: aurora
      DBClusterIdentifier:  !Ref Cluster
      DBSubnetGroupName:    !Ref SubnetGroup
      DBParameterGroupName: !Ref ParameterGroup
      DBInstanceClass:      !Ref DBInstanceClass
      EnablePerformanceInsights: true
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Role
          Value: !Ref Role
