AWSTemplateFormatVersion: '2010-09-09'

Description:
  AWS EC2 (AutoScaling) Resource

Parameters:
  ProjectName:
    Description: ""
    Type: String
  ImageId:
    Description: ""
    Type: String
    Default: "ami-d85e7fbf"
  InstanceType:
    Description: ""
    Type: String
    Default: "t2.micro"
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
  InstanceNum:
    Description: ""
    Type: String
    Default: "1"
  KeyPair:
    Description: ""
    Type: AWS::EC2::KeyPair::KeyName
  SubnetA:
    Description: ""
    Type: String
  SubnetC:
    Description: ""
    Type: String
  TargetGroupArn:
    Description: ""
    Type: String

Resources:
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPair
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            DeleteOnTermination: true
            VolumeType: "gp2"
      SecurityGroups:
        - { "Fn::ImportValue": !Sub "${ProjectName}-PublicSecurityGroup" }
      UserData:
        Fn::Base64: !Sub |
          #!/bin/sh
          set -x

          sudo apt-get update
          sudo apt-get install -y nginx
          sudo service nginx start

          # install cfn-signal
          pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
          cp -a /usr/local/init/ubuntu/cfn-hup /etc/init.d/cfn-hup
          chmod u+x /etc/init.d/cfn-hup

          # signal
          /usr/local/bin/cfn-signal -e 0 --stack ${AWS::StackName} --region ${AWS::Region} --resource AutoScalingGroup

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    CreationPolicy:
      ResourceSignal:
        Timeout: "PT10M"
    Properties:
      LaunchConfigurationName: !Ref LaunchConfiguration
      TargetGroupARNs:
        - !Ref TargetGroupArn
      DesiredCapacity: !Ref InstanceNum
      MaxSize: !Ref InstanceNum
      MinSize: !Ref InstanceNum
      VPCZoneIdentifier:
        - !Ref SubnetA
        - !Ref SubentC
      HealthCheckType: "EC2"
      HealthCheckGracePeriod: 60
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}.ec2"
          PropagateAtLaunch: true
        - Key: ProjectName
          Value: !Ref ProjectName
          PropagateAtLaunch: true
