AWSTemplateFormatVersion: '2010-09-09'

Description:
 AWS ELB Resource

Parameters:
 ProjectName:
  Description: ""
  Type: String
  Default: Dev

 DomainName:
  Description: ""
  Type: String

Resources:
 ApplicationLoadBalancer:
  Type: AWS::ElasticLoadBalancingV2::LoadBalancer
  Properties:
   Scheme: internet-facing
   SecurityGroups:
    - !Ref InternetSecurityGroup
   Subnets:
    - !Ref PublicSubnetA
    - !Ref PublicSubnetC
   Tags:
    - Key: Name
      Value: !Sub "ApplicationLoadBalancer-${ProjectName}"

 ApplicationLoadBalancerListener:
  Type: AWS::ElasticLoadBalancingV2::Listener
  Properties:
   LoadBalancerArn: !Ref ApplicationLoadBalancer
   Port: "80"
   Protocol: "HTTP"
   DefaultActions:
    - TargetGroupArn: !Ref ApplicationLoadBalancerTargetGroup
      Type: forward

 ApplicationLoadBalancerTargetGroup:
  Type: AWS::ElasticLoadBalancingV2::TargetGroup
  Properties:
   Port: "80"
   Protocol: "HTTP"
   VpcId: !Ref VPC

 Route53DNSRecord:
  Type: AWS::Route53::RecordSet
  Properties:
   Type: A
   AliasTaret:
    DNSName: !GetAtt ApplicationLoadBalancer.DNSName
    HostedZoneId: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
   Comment: ""
   HostedZoneName: !Join [ "", [!Ref DomainName, "."]]
   Name: !Join [ "", [!Ref ProjectName, ".", !Ref DomainName, "."]]
