AWSTemplateFormatVersion: '2010-09-09'

Description:
  AWS Frontend Resource

Parameters:
  ProjectName:
    Description: ""
    Type: String
  Environment:
    Description: ""
    Type: String
    Default: dev
  DomainName:
    Description: ""
    Type: String
    Default: "example.com"
  Role:
    Description: ""
    Type: String
    Default: default
