AWSTemplateFormatVersion: '2010-09-09'

Description:
  AWS S3 Resource

Parameters:
  ProjectName:
    Description: ""
    Type: String
    Default: example
  DomainName:
    Description: ""
    Type: String
    Default: "no-domain"

Outputs:
  ProjectName:
    Value: !Ref ProjectName
  S3BucketStaging:
    Description: ""
    Value: !Ref S3BucketStaging
    Export:
      Name: !Sub "${ProjectName}-S3BucketStaging"
  S3Bucket:
    Description: ""
    Value: !Ref S3Bucket
    Export:
      Name: !Sub "${ProjectName}-S3Bucket"
  S3Endpoint:
    Description: ""
    Value: !Ref S3Endpoint
    Export:
      Name: !Sub "${ProjectName}-S3Endpoint"

Resources:
  Staging:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-staging.${DomainName}"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}.${DomainName}.s3bucket.staging"
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: DomainName
          Value: !Ref DomainName

  Production:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}.${DomainName}"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}.${DomainName}.s3bucket"
        - Key: DomainName
          Value: !Ref DomainName

  VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: { "Fn::ImportValue": !Sub "${ProjectName}-VPC" }
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      RouteTableIds:
        - { "Fn::ImportValue": !Sub "${ProjectName}-PublicRouteTable" }
        - { "Fn::ImportValue": !Sub "${ProjectName}-PrivateRouteTable" }
