AWSTemplateFormatVersion: '2010-09-09'

Description:
 AWS SecurityGroup Resource

Parameters:
 ProjectName:
  Description: ""
  Type: String

Outputs:
 ProjectName:
  Value: !Ref ProjectName
 FrontendSecurityGroup:
  Value: !Ref FrontendSecurityGroup
  Export:
   Name: !Sub "${ProjectName}-sg-frontend"
 BackendSecurityGroup:
  Value: !Ref BackendSecurityGroup
  Export:
   Name: !Sub "${ProjectName}-sg-backend"

Resources:
 FrontendSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
   GroupDescription: "Frontend SecurityGroup"
   VpcId: { "Fn::ImportValue": !Sub "${ProjectName}-vpc" }
   SecurityGroupIngress:
    - CidrIp: "0.0.0.0/0"
      IpProtocol: "tcp"
      FromPort: "443"
      ToPort: "443"
    - CidrIp: "0.0.0.0/0"
      IpProtocol: "tcp"
      FromPort: "80"
      ToPort: "80"
    - CidrIp: "0.0.0.0/0"
      IpProtocol: "tcp"
      FromPort: "22"
      ToPort: "22"
   Tags:
    - Key: Name
      Value: !Sub "${ProjectName}-sg-frontend"
    - Key: ProjectName
      Value: !Ref ProjectName

 BackendSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
   GroupDescription: "Backend SecurityGroup"
   VpcId: { "Fn::ImportValue": !Sub "${ProjectName}-vpc" }
   SecurityGroupIngress:
     - SourceSecurityGroupId: !Ref FrontendSecurityGroup
       IpProtocol: "-1"
       FromPort: "-1"
       ToPort: "-1"
   Tags:
    - Key: Name
      Value: !Sub "${ProjectName}-sg-backend"
    - Key: ProjectName
      Value: !Ref ProjectName
