AWSTemplateFormatVersion: '2010-09-09'

Description:
  AWS Storage Resource

Parameters:
  ProductName:
    Description: ""
    Type: String
    Default: example
  Environment:
    Description: ""
    Type: String
    Default: dev
  Role:
    Description: ""
    Type: String
    Default: log
  DomainName:
    Description: ""
    Type: String
    Default: example.com

Outputs:
  ProductName:
    Value: !Ref ProductName
  S3BucketName:
    Value: !Ref S3Bucket
  VPCEndpoint:
    Value: !Ref VPCEndpoint

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Role}-${Environment}.${ProductName}.${DomainName}
      Tags:
        - Key: Name
          Value: !Sub ${Role}-${Environment}.${ProductName}.${DomainName}
        - Key: ProductName
          Value: !Ref ProductName
        - Key: Environment
          Value: !Ref Environment
        - Key: Role
          Value: !Ref Role
        - Key: DomainName
          Value: !Sub DomainName

  VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Sub '{{resolve:ssm:/${ProductName}/${Environment}/VPCID:1}}'
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      RouteTableIds:
        - !Sub '{{resolve:ssm:/${ProductName}/${Environment}/PublicRouteTable:1}}'
        - !Sub '{{resolve:ssm:/${ProductName}/${Environment}/PrivateRouteTable:1}}'

  SSMS3BucketName:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "PrivateSubnetA"
      Name: !Sub "/${ProductName}/${Environment}/storage/${Role}/S3BucketName"
      Value: !Sub ${Role}-${Environment}.${ProductName}.${DomainName}
      Type: String
