AWSTemplateFormatVersion: '2010-09-09'

Description:
  AWS Storage Resource

Parameters:
  ProjectName:
    Description: ""
    Type: String
    Default: "example"
  Environment:
    Description: ""
    Type: String
    Default: "dev"
  DomainName:
    Description: ""
    Type: String
    Default: "example.com"
  Role:
    Description: ""
    Type: String
    Default: "default"

Outputs:
  ProjectName:
    Value: !Ref ProjectName
  S3BucketName:
    Value: !Ref S3Bucket
  VPCEndpoint:
    Value: !Ref VPCEndpoint

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Role}-${Environment}.${ProjectName}.${DomainName}
      Tags:
        - Key: Name
          Value: !Sub ${Role}-${Environment}.${ProjectName}.${DomainName}
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Role
          Value: !Ref Role
        - Key: DomainName
          Value: !Sub DomainName

  VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Sub '{{resolve:ssm:/${ProjectName}/${Environment}/VPCID:1}}'
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      RouteTableIds:
        - !Sub '{{resolve:ssm:/${ProjectName}/${Environment}/PublicRouteTable:1}}'
        - !Sub '{{resolve:ssm:/${ProjectName}/${Environment}/PrivateRouteTable:1}}'

  SSMS3BucketName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "PrivateSubnetA"
      Name: !Sub "/${ProjectName}/${Environment}/storage/${Role}/S3BucketName"
      Value: !Sub ${Role}-${Environment}.${ProjectName}.${DomainName}
      Type: String
