AWSTemplateFormatVersion: '2010-09-09'

Description:
  AWS Subnet Resource

Parameters:
  ProjectName:
    Description: ""
    Type: String
    Default: example
  CidrBlock:
    Description: ""
    Type: String
    Default: 10.0.0.0/27
  AvailabilityZone:
    Description: ""
    Type: String
    Default: ap-northeast-1a
  MapPublicIpOnLaunch:
    Description: ""
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  AttachInternetGateway:
    Description: ""
    Type: String
    AllowedValues:
      - true
      - false

Conditions:
  IsPublic: !Equals [ !Ref AttachInternetGateway, "true" ]

Outputs:
  ProjectName:
    Value: !Ref ProjectName
  Subnet:
    Value: !Ref Subnet
    Export:
      Name: !Sub "${ProjectName}-Subnet"

Resources:
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: { "Fn::ImportValue": !Sub "${ProjectName}-VPC" }
      CidrBlock: !Ref CidrBlock
      AvailabilityZone: !Ref AvailabilityZone
      MapPublicIpOnLaunch: !Ref MapPublicIpOnLaunch
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}.subnet"
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: NetworkSegment
          Value: !If
            - IsPublic
            - "public"
            - "private"

  SubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !If
        - IsPublic
        - { "Fn::ImportValue": !Sub "${ProjectName}-PublicRouteTable" }
        - { "Fn::ImportValue": !Sub "${ProjectName}-PrivateRouteTable" }
