AWSTemplateFormatVersion: '2010-09-09'

Description:
 AWS VPC Resource

Parameters:
 ProjectName:
  Description: ""
  Type: String

 CidrBlockVPC:
  Description: ""
  Type: String
  Default: 10.0.0.0/16

 CidrBlockPublicSubnetA:
  Description: ""
  Type: String
  Default: 10.0.0.0/27

 CidrBlockPublicSubnetC:
  Description: ""
  Type: String
  Default: 10.0.0.32/27

 CidrBlockPrivateSubnetA:
  Description: ""
  Type: String
  Default: 10.0.0.64/27

 CidrBlockPrivateSubnetC:
  Description: ""
  Type: String
  Default: 10.0.0.96/27

Outputs:
 ProjectName:
  Value: !Ref ProjectName
  Export:
   Name: !Ref ProjectName
 VPC:
   Value: !Ref VPC
   Export:
    Name: !Sub "${ProjectName}-vpc"
 PublicRouteTable:
   Value: !Ref PublicRouteTable
   Export:
    Name: !Sub "${ProjectName}-rt-public"
 PrivateRouteTable:
   Value: !Ref PrivateRouteTable
   Export:
    Name: !Sub "${ProjectName}-rt-private"
 PublicSubnetA:
   Value: !Ref PublicSubnetA
   Export:
    Name: !Sub "${ProjectName}-subneta-public"
 PublicSubnetC:
   Value: !Ref PublicSubnetC
   Export:
    Name: !Sub "${ProjectName}-subnetc-public"
 PrivateSubnetA:
   Value: !Ref PrivateSubnetA
   Export:
    Name: !Sub "${ProjectName}-subneta-private"
 PrivateSubnetC:
   Value: !Ref PrivateSubnetC
   Export:
    Name: !Sub "${ProjectName}-subnetc-private"


Resources:
 VPC:
  Type: AWS::EC2::VPC
  Properties:
   CidrBlock: !Ref CidrBlockVPC
   EnableDnsSupport: "true"
   EnableDnsHostnames: "true"
   InstanceTenancy: default
   Tags:
    - Key: Name
      Value: !Sub "${ProjectName}-vpc"
    - Key: ProjectName
      Value: !Ref ProjectName

 PublicRouteTable:
  Type: AWS::EC2::RouteTable
  Properties:
   VpcId: !Ref VPC
   Tags:
    - Key: Name
      Value: !Sub "${ProjectName}-rt-public"
    - Key: ProjectName
      Value: !Ref ProjectName

 PrivateRouteTable:
  Type: AWS::EC2::RouteTable
  Properties:
   VpcId: !Ref VPC
   Tags:
    - Key: Name
      Value: !Sub "${ProjectName}-rt-private"
    - Key: ProjectName
      Value: !Ref ProjectName

 PublicSubnetA:
  Type: AWS::EC2::Subnet
  Properties:
   VpcId: !Ref VPC
   CidrBlock: !Ref CidrBlockPublicSubnetA
   AvailabilityZone: !Select [ "0", !GetAZs ""]
   MapPublicIpOnLaunch: true
   Tags:
    - Key: Name
      Value: !Sub "${ProjectName}-subneta-public"
    - Key: ProjectName
      Value: !Ref ProjectName

 PublicSubnetARouteTableAssociation:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
   SubnetId: !Ref PublicSubnetA
   RouteTableId: !Ref PublicRouteTable

 PublicSubnetC:
  Type: AWS::EC2::Subnet
  Properties:
   VpcId: !Ref VPC
   CidrBlock: !Ref CidrBlockPublicSubnetC
   AvailabilityZone: !Select [ "2", !GetAZs ""]
   MapPublicIpOnLaunch: true
   Tags:
    - Key: Name
      Value: !Sub "${ProjectName}-subnetc-public"
    - Key: ProjectName
      Value: !Ref ProjectName

 PublicSubnetCRouteTableAssociation:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
   SubnetId: !Ref PublicSubnetC
   RouteTableId: !Ref PublicRouteTable

 PrivateSubnetA:
  Type: AWS::EC2::Subnet
  Properties:
   VpcId: !Ref VPC
   CidrBlock: !Ref CidrBlockPrivateSubnetA
   AvailabilityZone: !Select [ "0", !GetAZs ""]
   Tags:
    - Key: Name
      Value: !Sub "${ProjectName}-subneta-private"
    - Key: ProjectName
      Value: !Ref ProjectName

 PrivateSubnetARouteTableAssociation:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
   SubnetId: !Ref PrivateSubnetA
   RouteTableId: !Ref PrivateRouteTable

 PrivateSubnetC:
  Type: AWS::EC2::Subnet
  Properties:
   VpcId: !Ref VPC
   CidrBlock: !Ref CidrBlockPrivateSubnetC
   AvailabilityZone: !Select [ "2", !GetAZs ""]
   Tags:
    - Key: Name
      Value: !Sub "${ProjectName}-subnetc-private"
    - Key: ProjectName
      Value: !Ref ProjectName

 PrivateSubnetCRouteTableAssociation:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
   SubnetId: !Ref PrivateSubnetC
   RouteTableId: !Ref PrivateRouteTable

 InternetGateway:
  Type: AWS::EC2::InternetGateway
  Properties:
   Tags:
    - Key: Name
      Value: !Sub "${ProjectName}.igw"
    - Key: ProjectName
      Value: !Ref ProjectName

 AttachGateway:
  Type: AWS::EC2::VPCGatewayAttachment
  Properties:
   InternetGatewayId: !Ref InternetGateway
   VpcId: !Ref VPC

 Route:
  Type: AWS::EC2::Route
  Properties:
   RouteTableId: !Ref PublicRouteTable
   DestinationCidrBlock: 0.0.0.0/0
   GatewayId: !Ref InternetGateway
