AWSTemplateFormatVersion: "2010-09-09"

Description: ""

Parameters:
  ImageID:
    Type: "AWS::EC2::Image::Id"
    Default: "ami-0f9af249e7fa6f61b"
    Description: "Ubuntu Server 16.04 LTS (HVM), SSD Volume Type"
  SubnetID:
    Type: "AWS::EC2::Subnet::Id"
    Description: ""
  KeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: ""
  InstanceType:
    Type: String
    Default: c5.large
    Description: ""

Resources:
  IAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"

  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - !Ref IAMRole

  LaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: "/dev/sda1"
            Ebs:
              DeleteOnTermination: true
              VolumeType: "gp2"
              VolumeSize: 8
        IamInstanceProfile:
          Arn: !GetAtt InstanceProfile.Arn
        ImageId: !Ref ImageID
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        InstanceMarketOptions:
          SpotOptions:
            SpotInstanceType: one-time
            InstanceInterruptionBehavior: terminate
          MarketType: spot
        UserData:
          Fn::Base64: |
            #!/bin/sh -x

            apt update && apt upgrade -y

            reboot

  SpotInstance1:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      SubnetId: !Ref SubnetID
      Tags:
        - Key: Name
          Value: !Sub "spot.${InstanceType}"

  SpotInstance2:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      SubnetId: !Ref SubnetID
      Tags:
        - Key: Name
          Value: !Sub "spot.${InstanceType}"
